### ISSUE TITLE
No reading from PMS7003

### ISSUE THREAD

**Issue by DrBlokmeister** [nkitanov/iaq_board#20]
Hey! First of all thanks for your work on this project. I really appreciate it. It's the first time I ordered a custom PCB and I hope it will bring me to making more custom devices.

I have ordered your PCB, with the D1 mini ESP32, the MH-Z19 and PMS7003. Other sensors/components are still on their way. 

Therefore I use a limited part of your config:
```YAML
uart:
  - rx_pin: GPIO1
    baud_rate: 9600
    id: pms
  
  - rx_pin: GPIO18
    tx_pin: GPIO19
    baud_rate: 9600
    id: mh


sensor:
    - platform: pmsx003
      type: PMSX003
      uart_id: pms
      pm_1_0:
        name: "PM 1 Concentration"
        id: pm1
      pm_2_5:
        name: "PM 2.5 Concentration"
        id: pm2_5
      pm_10_0:
        name: "PM 10 Concentration"
        id: pm10

    - platform: mhz19
      co2:
        name: "CO2"
        id: co2
      temperature:
        name: "MH-Z19 Temperature"
      update_interval: 10s
      automatic_baseline_calibration: false
      uart_id: mh
      id: mh_sensor

switch:
  - platform: gpio
    name: "PMS7003_SET"
    pin: 
      number: GPIO26
      mode: OUTPUT
    restore_mode: ALWAYS_ON
    id: pms_set
```

The readings from the CO2 sensor are just fine and roughly what I expect. However, I get no reading from the PMS7003.

Some observations:

- The fan of the PMS7003 is running, so I assume that 5V and GND are connected correctly
- Using a multimeter, I measured:
  - 0.4 Ohm between the two 5V pins (of PCB header)
  - 0.4 Ohm between the two GND pins (of PCB header)
  - open loop between 5V and GND pins (of PCB header)
  - open loop or >MOhm between other pin combinations (of PCB header)
  - 0.4 Ohm between GPIO1 on Wemos D1 and pin9 of PCB header
From this I conclude that galvanically, the connections should be fine.

I've thought about my PMS7003 being faulty, but I have no way to double check as I have no 1.25 mm pitch headers/converter cables.

I read somewhere online about pulling up the set pin. Is this required for this board?

Is there something else I should check before ordering a new sensor?

**Comment by DrBlokmeister** [comment]
I got it working. I wedged a 10 kOhm resistor between 3.3V and GPIO18 and changed the switch configuration to pin18:

```YAML
switch:
  - platform: gpio
    name: "PMS7003_SET"
    pin: 
      number: GPIO18
      mode: OUTPUT
    restore_mode: ALWAYS_ON
    id: pms_set
```

I think your standard YAML file is wrong, as you need to use GPIO18 and not GPIO26.

Otherwise this issue can be closed.
